apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-prediction-stream
spec:
  selector:
    matchLabels:
      app: airline-prediction-stream
  replicas: 1
  template:
    metadata:
      labels:
        app: airline-prediction-stream
    spec:
      containers:
      - name: airline-prediction-stream
        image: ably77/airlineprediction-stream:latest
