apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: myproject-dev

bases:
- ../../../../manifests/app/backend/strimzi-kafka-service/base

resources:
# uncomment below if you want to deploy the mirrormaker2 demo
- mm2-target-kafka.yaml
- mm2.yaml
- mm2-consumer.yaml