apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metering-ocp 
  namespace: openshift-metering 
spec:
  channel: "4.5" 
  source: "redhat-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "metering-ocp"
  installPlanApproval: "Automatic" 