apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: bookinfo

bases:
- ../../../../manifests/app/frontend/book-info-app/base

resources:
- namespace.yaml
- destination-rule-all.yaml

# apply the configurations below to demo service mesh in action
#
# user-story: route all traffic to v1
# A virtual service defines a set of traffic routing rules to apply when a host is addressed. 
# This includes the service version, in this case version 1 of all services (version 1 of Reviews, with no stars)
#- demo/virtual-service-all-v1.yaml
#
# use-case: distinguish individual users in routing decisions
# Login as with credentials jason/jason. Refresh the webpage several times. 
# You'll only see version 2 black stars. Then logout. You'll only see version 3 red stars.
# demo/virtual-service-reviews-jason-v2-v3.yaml
#
# use-case: retire version 1 and send traffic to v2 and v3 50/50
# Refresh the webpage repeatedly. We see half the results show red and half with black stars as expected.
- demo/virtual-service-reviews-v2-v3.yaml
#
# use-case: 100% traffic to v3
# Refresh the webpage repeatedly. You'll only see version 3 red stars.
#- demo/virtual-service-reviews-v3.yaml
#
# use-case: fault injection
# Apply a fault injection on our details microservice to always return an error - a HTTP status of 555
#- demo/fault-injection-details-v1.yaml