# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- iotdemo-app.yaml
- kafka-loadtest-app.yaml
- manuela-line-dashboard-app.yaml
- manuela-machine-sensor-app.yaml
- bookinfo-app.yaml

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: iotdemo-app
    namespace: argocd
  path: meta/patches/github-username-patch.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: kafka-loadtest-app
    namespace: argocd
  path: meta/patches/github-username-patch.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: bookinfo-app
    namespace: argocd
  path: meta/patches/github-username-patch.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: manuela-line-dashboard
    namespace: argocd
  path: meta/patches/github-username-patch.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: manuela-machine-sensor
    namespace: argocd
  path: meta/patches/github-username-patch.yaml