# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- amq-broker-cr.yaml
- messaging-configmap.yaml
- messaging-deployment.yaml
- messaging-svc.yaml
- route.yaml



