apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# uncomment if you want to deploy kubeflow components
# note that this may clash with any existing deployment of istio in istio-system
#- cr/kfctl_openshift.v1.2.0.yaml
- kfdef-cr.yaml